### ISSUE TITLE
Pasar egresos - CRP a microservicio en presupuesto_mid

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/presupuesto_mid#1]

**Comment by JuanPiedrahita** [comment]
Se agrega endpoint de registro presupuestal para consulta de crps ([commit](https://github.com/udistrital/presupuesto_mid/commit/fe81a53e00481fdf15ebf35bd044250c9d6ea4ed)).

**Comment by miguelramirez93** [comment]
Revisado. No se tienen observaciones.
