### ISSUE TITLE
Pasar ingresos de presupuesto a microservicio - mid

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/presupuesto_mid#2]
Pasar endpoints de ingresos de mid de financiera al mid de presupuesto.

**Comment by JuanPiedrahita** [comment]
Revisión de variables de entorno para conexión con servicios externos.

[Ajustes propios.](https://github.com/udistrital/presupuesto_mid/commit/085b4cebc393140bd8b9690c9cb59bf6d40f91a7)

[Revisión con lider técnico](https://github.com/udistrital/presupuesto_mid/commit/3d44728f32d311108a3b6d5a887a3a7cc7b0a430) @miguelramirez93

**Comment by JuanPiedrahita** [comment]
Ajustes para consulta de ingresos sin situación de fondos [commit](https://github.com/udistrital/presupuesto_mid/commit/3417594a08be41fd1672520c158f90ad08bc85eb) .

**Comment by JuanPiedrahita** [comment]
Ajustes para registro de ingresos sin situación de fondos [commit ](https://github.com/udistrital/presupuesto_mid/commit/ce29db6e34e259b8100e1bcbc28bef630b847e36).

**Comment by miguelramirez93** [comment]
Favor revisar los comentarios en los commits y ajustar según lo requerido

**Comment by JuanPiedrahita** [comment]
Por favor validar si de esta forma estaría bien el ajuste de las url https://github.com/udistrital/presupuesto_mid/commit/d0e2d1adaa116093656082de1aeaad32b47903dd

**Comment by miguelramirez93** [comment]
Se revisa y aprueba sin observaciones
