### ISSUE TITLE
Pasar egresos - CDP a microservicio - Mid

### ISSUE THREAD

**Issue by JuanPiedrahita** [udistrital/presupuesto_mid#3]
Pasar endpoints de ingresos de mid de financiera al mid de presupuesto.

**Comment by JuanPiedrahita** [comment]
Ajustes de endopoints, modelos y controladores para solicitud de CDP's https://github.com/udistrital/presupuesto_mid/commit/f51df136e32ec7f753cb26aadb635e6d2bd43705.

**Comment by JuanPiedrahita** [comment]
Ajustes de endopoints, modelos y controladores para consulta y anulación de CDP's https://github.com/udistrital/presupuesto_mid/commit/ce29db6e34e259b8100e1bcbc28bef630b847e36.

**Comment by miguelramirez93** [comment]
Favor revisar los comentarios en los commit y ajustar según lo requerido

**Comment by JuanPiedrahita** [comment]
Por favor validar si de esta forma estaría bien el ajuste de las url https://github.com/udistrital/presupuesto_mid/commit/d0e2d1adaa116093656082de1aeaad32b47903dd

**Comment by miguelramirez93** [comment]
Revisado. No se tienen observaciones
